"""Add city/area/address cascade and validation

Revision ID: ca6c04f12319
Revises: 
Create Date: 2026-05-09 00:46:44.453180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6c04f12319'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('addresses_city_id_fkey'), 'addresses', type_='foreignkey')
    op.drop_constraint(op.f('addresses_area_id_fkey'), 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'areas', ['area_id'], ['area_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'addresses', 'cities', ['city_id'], ['city_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('areas_city_id_fkey'), 'areas', type_='foreignkey')
    op.create_foreign_key(None, 'areas', 'cities', ['city_id'], ['city_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'areas', type_='foreignkey')
    op.create_foreign_key(op.f('areas_city_id_fkey'), 'areas', 'cities', ['city_id'], ['city_id'])
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key(op.f('addresses_area_id_fkey'), 'addresses', 'areas', ['area_id'], ['area_id'])
    op.create_foreign_key(op.f('addresses_city_id_fkey'), 'addresses', 'cities', ['city_id'], ['city_id'])
    # ### end Alembic commands ###
