"""sync notifications schema

Revision ID: f63ff6afcc89
Revises: a1b2c3d4e5f6
Create Date: 2026-06-22 14:43:34.631848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63ff6afcc89'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('recipient_type', sa.String(length=20), nullable=False))
    op.add_column('notifications', sa.Column('body', sa.String(length=500), nullable=False))
    op.add_column('notifications', sa.Column('data', sa.JSON(), nullable=True))
    op.add_column('notifications', sa.Column('read_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column(
        'notifications',
        'notification_type',
        existing_type=sa.VARCHAR(length=60),
        type_=sa.Enum(
            'public_lead_created',
            'public_lead_slots_full',
            'public_lead_expired',
            'public_lead_closed_matched',
            'public_lead_closed_no_match',
            'new_offer_received',
            'offer_accepted',
            'offer_rejected',
            'offer_slot_opened',
            'private_lead_received',
            'private_lead_accepted',
            'private_lead_rejected',
            'new_tutor_pending',
            'tutor_verified',
            'tutor_verification_rejected',
            name='notificationtype',
        ),
        existing_nullable=False,
        postgresql_using='notification_type::notificationtype',
    )
    op.drop_column('notifications', 'related_type')
    op.drop_column('notifications', 'actor_id')
    op.drop_column('notifications', 'actor_role')
    op.drop_column('notifications', 'related_id')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'recipient_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('recipient_role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('related_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('actor_role', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('related_type', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.Enum('public_lead_created', 'public_lead_slots_full', 'public_lead_expired', 'public_lead_closed_matched', 'public_lead_closed_no_match', 'new_offer_received', 'offer_accepted', 'offer_rejected', 'offer_slot_opened', 'private_lead_received', 'private_lead_accepted', 'private_lead_rejected', 'new_tutor_pending', 'tutor_verified', 'tutor_verification_rejected', name='notificationtype'),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'data')
    op.drop_column('notifications', 'body')
    op.drop_column('notifications', 'recipient_type')
    # ### end Alembic commands ###
